### ISSUE TITLE
Warning when compiling with Elixir 1.11.0-rc.0

### ISSUE THREAD

**Issue by wingyplus** [elixirmoney/money#150]
I found warnings when try to compile with Elixir 1.11.0-rc.0:

```
==> money
Compiling 11 files (.ex)
warning: redefining @doc attribute previously set at line 265.
Please remove the duplicate docs. If instead you want to override a previously defined @doc, attach the @doc attribute to a function head:
    @doc """
    new docs
    """
    def get(...)
  lib/money/currency.ex:278: Money.Currency.get/1
warning: incompatible types:
    %Money{} !~ atom()
in expression:
    # lib/money/ecto/map_type.ex:36
    money.amount()
where "money" was given the type %Money{} in:
    # lib/money/ecto/map_type.ex:35
    %Money{} = money
where "money" was given the type atom() (due to calling var.fun()) in:
    # lib/money/ecto/map_type.ex:36
    money.amount()
HINT: "var.field" (without parentheses) implies "var" is a map() while "var.fun()" (with parentheses) implies "var" is an atom()
Conflict found at
  lib/money/ecto/map_type.ex:36: Money.Ecto.Map.Type.dump/1
Generated money app
```

**Comment by wingyplus** [comment]
For redefining @doc warning, I think we need to declare no body clause function for `get/1` and rephase in documentation.

**Comment by Nitrino** [comment]
@wingyplus Yep @doc should be defined for `get/1` no body clause function.
Will you send a pull request?

**Comment by wingyplus** [comment]
Sure i will

**Comment by wingyplus** [comment]
@Nitrino The PR was open. I just copy the example from the second match of `get/1` because it doesn't raise ArgumentError as it said in the doc.
